apiVersion: v1
kind: Service
metadata:
  name: service-prod
  labels:
    app: blue-test
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    #app: blue-test
    slot: {{ .Values.productionSlot }}
