{{ if .Values.green.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
  labels:
    release: {{ .Release.Name }}
    app: green-test
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: green-test
      release: {{ .Release.Name }}
      slot: green 
  template:
    metadata:
      labels:
        app: green-test
        release: {{ .Release.Name }}
        slot: green
    spec:
      containers:
        - name: test-green
          image: {{ .Values.green.image }}:{{ .Values.green.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # This (and the volumes section below) mount the config map as a volume.
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: wwwdata-volume
      volumes:
        - name: wwwdata-volume
          configMap:
            name: test-green
{{ end }}