
name: build nginx

# ручной запуск
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: |
          cp .env_example.env .env
          docker-compose build nginx

      - name: Push build 
        run: |
          cp .env_example.env .env
          docker login -u ${{ secrets.GIHUB_USERNAME }} -p "${{ secrets.GIHUB_PASSWORD }}"
          docker-compose push 

  deploy:
    if: github.ref == 'refs/heads/master'
    name: Run remote deploy script
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Deploy 
        run: echo 'deploy'        
