
name: build nginx

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: |
          cp .env_example.env .env
          docker-compose build nginx
